### ISSUE TITLE
lxml 3.6.1 problem on windows

### ISSUE THREAD

**Issue by dipterix** [WattTime/pyiso#108]
You are using 
lxml = 3.6.1
as package prerequisite, but 3.6.1 has some problems on windows (compile error). I changed your source code and tried 3.6.4 and it worked.
Therefore I suggest maybe we could change the requirement to 
lxml>=3.6.1

**Comment by dipterix** [comment]
My colleagues also have the problem installing lxml 3.6.1 on their computers.

**Comment by r24mille** [comment]
#135 fixed this issue. @ajdonnison, it can be closed. I should have used the ["fixes" keyword to automatically close it](https://help.github.com/articles/closing-issues-using-keywords/).
