### ISSUE TITLE
Error DST on NYISO (get_lmp DAHR on october 1st)

### ISSUE THREAD

**Issue by nlejeune** [WattTime/pyiso#111]
File "pandas/tslib.pyx", line 4352, in pandas.tslib.tz_localize_to_utc (pandas/tslib.c:75236)
pytz.exceptions.AmbiguousTimeError: There are 29 dst switches when there should only be 1.

**Comment by nlejeune** [comment]
I called nyiso.get_lmp(start_at=start_at, end_at=end_at, node_id=data_node_list[i], market=market)
With start_at = 2000-10-01 00:00:00
And end_at = 2000-10-01 23:59:59
and market = 'DAHR'
node_id = one of the NYISO node  :)

**Comment by r24mille** [comment]
@ajdonnison, this older issue can probably be closed since the base `get_lmp(...)` method is no longer supported. I missed tagging this issue in #168.

**Comment by ajdonnison** [comment]
Closing due to `get_lmp` no longer available.
