### ISSUE TITLE
nyiso parse_genmix fails with KeyError

### ISSUE THREAD

**Issue by systemcatch** [WattTime/pyiso#180]
See [here](https://github.com/tmrowco/electricitymap/issues/864) for background information.  It looks like the parse_genmix method in nyiso.py is failing with a KeyError on https://github.com/WattTime/pyiso/blob/master/pyiso/nyiso.py#L271.

Taking a look at the [csv data](http://mis.nyiso.com/public/P-63list.htm) it seems like one of the column headers has been renamed hence the error.

**Comment by r24mille** [comment]
Hi @systemcatch, thanks for the bug report. I saw you forked pyiso. Were you planning on working through this bug and opening a pull request? Otherwise, I may be able to dig into this bug in the next few days.

Also, great to see someone from electricitymap pop in, cheers!

**Comment by systemcatch** [comment]
Hey @r24mille I'm pretty busy the next few days so won't have much time to work on it.  Cool project you've got here, I'd like to dig into the code more.  We're trying to add all the various USA ISO's to the map atm rather than aggregating at the country level.
