### ISSUE TITLE
Where did get_lmp go?

### ISSUE THREAD

**Issue by Kladar** [WattTime/pyiso#189]
Why was get_lmp removed and did this functionality move elsewhere?

**Comment by ebraswell** [comment]
As noted in the PyISO code, we have a statement here: http://watttime.org/lmp/

**Comment by bendichter** [comment]
I read the statement, and I understand your reasons for making the change. In fact, I did not know that optimizing for LMP could be harmful, so you taught me something there. However, it's hard to make a case to real companies to change the way they use energy without a cost/savings estimate, and it's hard to get that estimate without LMP data. I was really excited to find this package, and I've been using it successfully for months. It's a shame I won't be able to follow active development anymore for my use-case.

**Comment by claytonpbarrows** [comment]
I'm in agreement with @bendichter. I understand the shortcomings of the LMP metric. However, it's unfortunate that he watttime team fails to recognize the usefulness of the pyiso package as LMP remains a useful metric for a variety of analysis.

**Comment by ebraswell** [comment]
While we understand that some people found PyISO useful beyond it's intended functionality, we are a non-profit with a specific mission - to reduce the environmental impact of electricity production. LMP data not only doesn't serve that mission, but can be used in ways that run counter to it. At the end of the day we are not a data provider and LMP data is easily and readily found elsewhere.

**Comment by bendichter** [comment]
Is there a library you would recommend? If you google "lmp power data python" this library is 4 out of the 5 top results. @claytonpbarrows have you found an alternative tool?

**Comment by claytonpbarrows** [comment]
I have not found an alternative tool. I have a fork of an older version of this repo at github.com/claytonpbarrows/PyISO that still has working get_lmp() methods (tested 'CAISO' today). I'd be interested in paths forward/alternative that include maintaining the get_lmp() methods.

**Comment by vitormhenrique** [comment]
Hello, I Just found this library, and saw that LMP was removed, unfortunately the link with some explanation and text was also removed..... 

Is there a copy of some documentation that I could read regarding this?

 http://watttime.org/lmp/ is offline
