### ISSUE TITLE
CAISO file should support 15-minute market

### ISSUE THREAD

**Issue by jkhooker** [WattTime/pyiso#42]
I want to be able to pull 15-minute LMP data. I am able to modify the code to accomplish this, but I recommend adding it as a feature. Here is the CAISO OASIS URL that accomplishes my task:

http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTPD_LMP&startdatetime=20150901T00:00-0700&enddatetime=20151001T00:00-0700&market_run_id=RTPD&version=1&resultformat=6

The key differences from the 5-minute market are "PRC_RTPD_LMP" and "RTPD"

**Comment by jkhooker** [comment]
This may shed some light on your comment "# There are actually three codes used: RTPD (Real-time Pre-dispatch), RTD (real-time dispatch), and RTM (Real-Time Market). I can't figure out what the difference is."

**Comment by aschn** [comment]
That would be a good feature, thanks for suggesting it! If you've already made the modification, can you submit a pull request?

**Comment by jkhooker** [comment]
I would, but my changes to the caiso.py file are more of a hack than an elegant solution. In caiso.py, I did the following:

In get_lmp(...), I made this edit:
'lmp': row['PRC'], # switched from LMP_PRC

In LMP_MARKETS, I added this line:
'RTPD': 'PRC_RTPD_LMP',

And then I did this when actually getting the price data:
data = caiso.get_lmp(start_at=datetime(2014, 9, 1), end_at=datetime(2014, 9, 2) , market="RTPD", market_run_id="RTPD")

I have a feeling this is not even correct, but just thought I would share what I did (hopefully to save you time if you choose to implement)

**Comment by r24mille** [comment]
@ajdonnison, another issue that can now be closed since we no longer support `get_lmp()`. I missed closing this issue with others in #168.

**Comment by ajdonnison** [comment]
As per @r24mille this is no longer relevant.
