### ISSUE TITLE
`get_lmp_as_dataframe` returns `pandas.DataFrame` instead of `pandas.DataFrame()` in some cases

### ISSUE THREAD

**Issue by kinghajj** [WattTime/pyiso#62]
This caused a type error to occur in code at work that assumed the return value is always a DataFrame instance, and not the DataFrame class object.

https://github.com/WattTime/pyiso/blob/566506dbd5e2c16b96f129fea007c38aea430f4c/pyiso/caiso.py#L263
https://github.com/WattTime/pyiso/blob/566506dbd5e2c16b96f129fea007c38aea430f4c/pyiso/caiso.py#L281

**Comment by ndavis6** [comment]
Hi kinghajj,  can you check out the PR and see if it fixes your problem?
